/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicUploadApkRouteImport } from './routes/api/public/upload-apk'
import { Route as ApiPublicRadioTtsRouteImport } from './routes/api/public/radio-tts'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicUploadApkRoute = ApiPublicUploadApkRouteImport.update({
  id: '/api/public/upload-apk',
  path: '/api/public/upload-apk',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRadioTtsRoute = ApiPublicRadioTtsRouteImport.update({
  id: '/api/public/radio-tts',
  path: '/api/public/radio-tts',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/download': typeof DownloadRoute
  '/reset-password': typeof ResetPasswordRoute
  '/api/public/radio-tts': typeof ApiPublicRadioTtsRoute
  '/api/public/upload-apk': typeof ApiPublicUploadApkRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/download': typeof DownloadRoute
  '/reset-password': typeof ResetPasswordRoute
  '/api/public/radio-tts': typeof ApiPublicRadioTtsRoute
  '/api/public/upload-apk': typeof ApiPublicUploadApkRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/download': typeof DownloadRoute
  '/reset-password': typeof ResetPasswordRoute
  '/api/public/radio-tts': typeof ApiPublicRadioTtsRoute
  '/api/public/upload-apk': typeof ApiPublicUploadApkRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/download'
    | '/reset-password'
    | '/api/public/radio-tts'
    | '/api/public/upload-apk'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/download'
    | '/reset-password'
    | '/api/public/radio-tts'
    | '/api/public/upload-apk'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/download'
    | '/reset-password'
    | '/api/public/radio-tts'
    | '/api/public/upload-apk'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DownloadRoute: typeof DownloadRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicRadioTtsRoute: typeof ApiPublicRadioTtsRoute
  ApiPublicUploadApkRoute: typeof ApiPublicUploadApkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/upload-apk': {
      id: '/api/public/upload-apk'
      path: '/api/public/upload-apk'
      fullPath: '/api/public/upload-apk'
      preLoaderRoute: typeof ApiPublicUploadApkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/radio-tts': {
      id: '/api/public/radio-tts'
      path: '/api/public/radio-tts'
      fullPath: '/api/public/radio-tts'
      preLoaderRoute: typeof ApiPublicRadioTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DownloadRoute: DownloadRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicRadioTtsRoute: ApiPublicRadioTtsRoute,
  ApiPublicUploadApkRoute: ApiPublicUploadApkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
